version: '3.8'

services:
  backend-app:
    build: .
    container_name: movie-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/movie?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Ishar@120824
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - JWT_SECRET=MyJwtSecretKey@12345
      - JWT_EXPIRATION=3600000
    depends_on:
      - mysqldb
    networks:
      - movie-network

  mysqldb:
    image: mysql:8.0
    container_name: movie-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Ishar@120824
      - MYSQL_DATABASE=movie
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - movie-network
    command: --default-authentication-plugin=mysql_native_password

networks:
  movie-network:
    driver: bridge

volumes:
  mysql-data: